# Generated by Django 4.0.3 on 2022-06-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes_Letter_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_number_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Foot_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('qtd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardstore.clothes_letter_size')),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('qtd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardstore.clothes_number_size')),
            ],
        ),
        migrations.CreateModel(
            name='Hoobies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('qtd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardstore.clothes_letter_size')),
            ],
        ),
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('qtd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardstore.foot_size')),
            ],
        ),
    ]
